name: Generate GitHub Metrics

on:
  schedule: [{cron: "0 */12 * * *"}]  # Every 12 hours
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: axtr05
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          config_display: large
          config_theme: dark
          config_twemoji: yes
          config_octicon: yes
          config_padding: 20

          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_display: compact
          plugin_projects: yes
          plugin_projects_limit: 3
          plugin_projects_repositories: "axtr05/*"
          plugin_repositories_forks: yes
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_traffic: yes

          # PageSpeed Insights
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://axtr05.github.io
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_pwa: yes
          plugin_pagespeed_screenshot: yes

          # Music (optional)
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          plugin_music_limit: 2
          plugin_music_mode: recent

          # 3D Contributions
          plugin_contrib: yes
          plugin_contrib_3d: yes

          config_order: base.header, base.activity, base.community, base.repositories, base.metadata, plugin_languages, plugin_achievements, plugin_calendar, plugin_contrib, plugin_pagespeed, plugin_music, plugin_projects
