name: GitHub Metrics

on:
  # Update once a day at 00:00 UTC
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["main", "master"] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Replace "axtr05" with your GitHub username if different
          token: ${{ secrets.METRICS_TOKEN }}
          user: axtr05
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_colors: github
          plugin_languages_threshold: 2%
          plugin_languages_limit: 10
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          plugin_lines: yes
          plugin_stargazers: yes
          plugin_followup: yes
          plugin_traffic: yes
          plugin_reactions: yes
          plugin_repositories: 100
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          plugin_topics_limit: 12
          config_display: large
          config_order: base.header, isocalendar, languages, achievements, lines, topics, followup, stargazers
          plugin_support: yes
          plugin_notable: yes
          config_theme: react-dark
